name: pipeline app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm --prefix frontend install
      - run: npm --prefix frontend run build
      - run: cd frontend && npx next export
      - uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: frontend/out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ASIAQC2PIEBOBSBOZXZY
      AWS_SECRET_ACCESS_KEY: RRX1/+YXiD9kQrnvoEd8fGOatUjrbHHJlYICEqKl
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEJj//////////wEaDO847+gArjumZ5vIICK9AVr3BJoegvAygmyoZVOik/Ezd5yti/jFVagUdZ0MZOqxyjcuy3oxNIjJwqb9D6cWHLs6hbgbvY2n3KtdGn/x1jWMdjHpP8ldd8a0NPX7FHIayEXdUC97LEBRTYv2lQEqyb8VEI1540Hdo2eFAJkwlKBVTmTe5u+nZpugey83oeqHv8NO0n5k68CDKUyQlsKsglILRQ34EmEzcDUGHo7ebGMbmbd3qH2mDJdr/kvN9DBz2+lTXfPvyA3wSRUegyim5JiSBjItKw3bMfuXI4rM6/tMG9x1we/hIP24fUlC3DsgO85zapRiMnN1NBcyDMBmvZuO
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deploy
          path: frontend/out
      - run: aws s3 cp frontend/out s3://devops-cyo --recursive --acl public-read
